SET C51INC=e:\Keil_v5\C51\Inc;e:\Keil_v5\C51\Inc\STC
SET C51LIB=e:\Keil_v5\C51\Lib
SET CPU_TYPE=STC15W408AS
SET CPU_VENDOR=STC
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x02160EC0
"e:\Keil_v5\C51\BIN\C51.EXE" @.\build\main.__i
"e:\Keil_v5\C51\BIN\C51.EXE" @.\build\REY_CO~1.__I
"e:\Keil_v5\C51\BIN\C51.EXE" @.\build\delay.__i
"e:\Keil_v5\C51\BIN\C51.EXE" @.\build\LCD1602B.__i
"e:\Keil_v5\C51\BIN\C51.EXE" @.\build\USART.__i
"e:\Keil_v5\C51\BIN\C51.EXE" @.\build\timer.__i
"e:\Keil_v5\C51\BIN\BL51.EXE" @.\build\WIFI_F~1.LNP
"e:\Keil_v5\C51\BIN\OH51.EXE" ".\build\Wifi_Flow" 
