SET C51INC=e:\Keil_v5\C51\Inc;e:\Keil_v5\C51\Inc\STC
SET C51LIB=e:\Keil_v5\C51\Lib
SET CPU_TYPE=STC15W408AS
SET CPU_VENDOR=STC
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x02160EC0
"e:\Keil_v5\C51\BIN\C51.EXE" @main.__i
"e:\Keil_v5\C51\BIN\C51.EXE" @REY_CO~1.__I
"e:\Keil_v5\C51\BIN\C51.EXE" @delay.__i
"e:\Keil_v5\C51\BIN\C51.EXE" @LCD1602B.__i
"e:\Keil_v5\C51\BIN\C51.EXE" @USART.__i
"e:\Keil_v5\C51\BIN\C51.EXE" @timer.__i
"e:\Keil_v5\C51\BIN\BL51.EXE" @WIFI_F~1.LNP
"e:\Keil_v5\C51\BIN\OH51.EXE" "Wifi_Flow" 
